language: node_js

deploy:
  provider: npm
  email: hi@mynameisyuri.com
  api_key:
    secure: ${NPM_TOKEN}
  on:
    tags: true
    repo: oakslab/ooo-config-examples

notifications:
  email:
    on_success: change
    on_failure: always
